# Generated by Django 4.2.3 on 2023-07-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_ref', models.TextField(unique=True)),
                ('product_title', models.TextField()),
                ('product_slug', models.TextField()),
                ('product_category', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
